---
title: "Godambe.R"
author: "Maya S. Godambe"
date: "2022-10-17"
output: pdf_document
---
```{r}
# Loading Packages necessary for analyzing data
library(readr) 
library(package = "tidyverse")
library(package = "table1")
library(package = "descr")
library(package = "lsr")
require(SASxport)
library(foreign)
library(dplyr)
```

```{r}
#Loading data from git up repository use "read_csv" command. Data titled "titanic"
titanic<-read_csv("https://raw.githubusercontent.com/kijohnson/Data/main/titanic.csv")

#RECODE CLASS AS A FACTOR with levels, 1,2, and 3
titanic1 <- titanic %>%
  mutate(Pclass = recode_factor(.x = Pclass,
                                '1' = '1',
                                '2' = '2',
                                '3' = '3')) 
```
```{r}
# Class 1 has a median age of 38.5 years, Class 2 has a median age of 29 years, 
#and Class 3 has a median age of 24 years
aggregate(titanic1$Age,
          list(titanic1$Pclass),
          median)
```

```{r}
#boxplot of class by Age (years)
ggplot(data = titanic1, aes(x = Pclass, y = Age),
       group= Age) +
  geom_boxplot() +
  labs(x = "Class of Passengers", y = "Age (years)",  title = "Boxplot 1. Class by Age ")
```







